### ISSUE TITLE
Old member cleanup?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/gunicorn-feedstock#1]
Seeing the following message from the team update script. 

```
Checking gunicorn
AN OLD MEMBER (ocefpaf) NEEDS TO BE REMOVED FROM conda-forge/gunicorn-feedstock
```

ref: https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/191646830#L974-L975

cc @ocefpaf

**Comment by ocefpaf** [comment]
That is a pretty crappy script as members should be mainly focused at updating the version and that comes when it comes and not when the bot thinks it is timely.

**Comment by jakirkham** [comment]
Just to clarify that message is merely pointing out that you are included in the maintainer team of this feedstock, but not listed as a maintainer in the feedstock's recipe. Feel free to address it however you wish. Merely relaying the info.

**Comment by ocefpaf** [comment]
I understand that you have a lot of free time you your hands. That is not true in my case and please refrain from using @ocefpaf for useless messages like this one.
