### ISSUE TITLE
Request gunicorn 19.3.0

### ISSUE THREAD

**Issue by sodre** [conda-forge/gunicorn-feedstock#6]
Would it be possible to build a 19.3.0 version of gunicorn? I am trying to bring airflow into conda-forge but it has a hard dependency on >=19.3.0,<19.4.0, with a comment on a particular bug.

Thank you!

**Comment by ocefpaf** [comment]
Sure. Feel free to send a PR here. No need for a branch. We can just update to the latest version later.

**Comment by kwilcox** [comment]
Can you post details on the `gunicorn` bug? I run 19.6 for the `capture_output` config option (good for docker containers) and curious. I'm a heavy user of `luigi` but have thought about looking at `airflow` so thanks for taking the initiative!

**Comment by sodre** [comment]
@kwilcox, it non-descript [here](https://github.com/apache/incubator-airflow/blob/master/setup.py#L232). There are 5 revisions of 19.4, so they were probably up to something.

I tried with the other versions we have in conda-forge and other errors came up :(.

**Comment by kwilcox** [comment]
Closed vi https://github.com/conda-forge/gunicorn-feedstock/pull/7
